import type { RunState } from "../types/run";
import type { Pipeline } from "../types/pipeline";

function formatCostForReport(cost: number): string {
  if (cost < 0.01) return `$${cost.toFixed(4)}`;
  return `$${cost.toFixed(2)}`;
}

export function generateRunReport(
  runState: RunState,
  logs: Record<string, string[]>,
  pipeline?: Pipeline | null,
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Pipeline Run Report`);
  lines.push("");
  lines.push(`- **Pipeline**: ${runState.pipeline_name}`);
  lines.push(`- **Run ID**: ${runState.run_id}`);
  lines.push(`- **Status**: ${runState.status.toUpperCase()}`);
  lines.push(`- **Total Cost**: ${formatCostForReport(runState.total_cost_usd)}`);
  lines.push("");

  // Summary table
  const nodeResults = Object.values(runState.node_results);
  const succeeded = nodeResults.filter((r) => r.status === "Success").length;
  const failed = nodeResults.filter((r) => r.status === "Failed").length;
  const skipped = nodeResults.filter((r) => r.status === "Skipped").length;
  lines.push(`## Summary`);
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total nodes | ${nodeResults.length} |`);
  lines.push(`| Succeeded | ${succeeded} |`);
  lines.push(`| Failed | ${failed} |`);
  lines.push(`| Skipped | ${skipped} |`);
  lines.push("");

  // Per-node sections
  lines.push(`## Node Results`);
  lines.push("");

  const nodeOrder = pipeline?.nodes.map((n) => n.id) ?? Object.keys(runState.node_results);
  for (const nodeId of nodeOrder) {
    const result = runState.node_results[nodeId];
    if (!result) continue;

    const nodeName = pipeline?.nodes.find((n) => n.id === nodeId)?.name ?? nodeId;
    lines.push(`### ${nodeName}`);
    lines.push("");
    lines.push(`- **Status**: ${result.status}`);
    if (result.exit_code !== null && result.exit_code !== undefined) {
      lines.push(`- **Exit Code**: ${result.exit_code}`);
    }
    if (result.started_at && result.finished_at) {
      lines.push(`- **Started**: ${result.started_at}`);
      lines.push(`- **Finished**: ${result.finished_at}`);
    }
    if (result.attempt > 1) {
      lines.push(`- **Attempts**: ${result.attempt}`);
    }
    if (result.cost_usd != null && result.cost_usd > 0) {
      lines.push(`- **Cost**: ${formatCostForReport(result.cost_usd)}`);
    }

    const nodeLogs = logs[nodeId];
    if (nodeLogs && nodeLogs.length > 0) {
      lines.push("");
      lines.push("```");
      lines.push(nodeLogs.join("\n"));
      lines.push("```");
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by AgentFlow on ${new Date().toISOString()}*`);

  return lines.join("\n");
}
